### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by shuntera** [LRA-QC/intrusion-detection#1]
Tried it on my Raspberry Pi and got this error:

sudo ./detect.py 192.168.1.0/24 data.db
Traceback (most recent call last):
  File "./detect.py", line 84, in <module>
    getNmapScan(sys.argv[1])    #SCAN NETWORK
  File "./detect.py", line 34, in getNmapScan
    output = subprocess.run(["sudo","nmap","-v","-sn",range,"-oX",filename], capture_output=True)
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

**Comment by harperreed** [comment]
I had the same issue. Turns out that This parameter doesn't exist in python3.6 and below. You will need to upgrade your python to 3.7 and up. 

Source: 
https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output

**Comment by LRA-QC** [comment]
Thanks  harperreed  for the follow up. I will try to detect the Python version and implement a work around for Python < 3.7
